name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

env:
  AWS_EC2_USER: ubuntu
  AWS_EC2_HOST: 43.204.235.141
  MONGODB_URI: ${{secrets.MONGODB_URI}}
  GROQ_API_KEY: ${{secrets.GROQ_API_KEY}}
  FIREBASE_URL: ${{secrets.FIREBASE_URL}}
  FIREBASE_CERTIFICATE: ${{secrets.FIREBASE_CERTIFICATE}}
  GMAIL_ATTACHMENT_FOLDER_ID: ${{secrets.GMAIL_ATTACHMENT_FOLDER_ID}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: make .env
        run: 